version: "3"

services:
  client1:
    build:
      context: .
      dockerfile: client.Dockerfile

  client2:
    build:
      context: .
      dockerfile: client.Dockerfile

  loadbalancer:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    links:
      - client1
      - client2
    ports:
      - "83:80"
  # nginx_03:
  #     build: .
  #     ports:
  #         - "83:80"
