version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    image: ontapp
    ports:
      - "5000:5000"
  app1:
    container_name: app1
    image: ontapp
    restart: always
    ports:
      - "5001:5000"