
version: '3'

services:

  api01:
      build: .
      environment:
        - spring_profiles_active=${ACTIVE}
      volumes:
        - /data/api

  api02:
    build: .
    environment:
      - spring_profiles_active=${ACTIVE}
    volumes:
      - /data/api

  redis:
    image: redis
    hostname: redis
    restart: always

  loadbalancer-api:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    links:
      - api01
      - api02
      - redis
    ports:
      - "8585:80"