
version: '3'

services:

  api01:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - spring_profiles_active=${ACTIVE}
        - spring.datasource.username=${MYSQL_USERNAME}
        - spring.datasource.password=${MYSQL_PWD}
        - spring.datasource.url=${MYSQL_URL}
        - server.port=${APP_PORT}
      volumes:
        - /data/api

  api02:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring_profiles_active=${ACTIVE}
      - spring.datasource.username=${MYSQL_USERNAME}
      - spring.datasource.password=${MYSQL_PWD}
      - spring.datasource.url=${MYSQL_URL}
      - server.port=${APP_PORT}
    volumes:
      - /data/api

  api03:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring_profiles_active=${ACTIVE}
      - spring.datasource.username=${MYSQL_USERNAME}
      - spring.datasource.password=${MYSQL_PWD}
      - spring.datasource.url=${MYSQL_URL}
      - server.port=${APP_PORT}
    volumes:
      - /data/api



  redis:
    image: redis
    hostname: redis
    restart: always

  loadbalancer-api:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    links:
      - api01
      - api02
      - api03
      - redis
    ports:
      - "8585:80"
